spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/unit-test
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect